spring.application.name=online-voting-backend
server.port=${PORT:8090}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=never

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://dpg-d6qitqnkijhs73b6mik0-a.oregon-postgres.render.com:5432/online_voting_db_16rt}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sai}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:KX42fe6wwc9uTQqZpBDBSltvCP2wfeMk}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
