spring.application.name=online-voting-backend
server.port=8090

#spring.datasource.url=jdbc:mysql://localhost:3306/online_voting_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=manager
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.sql.init.mode=always


spring.datasource.url=jdbc:postgresql:dpg-d6qitqnkijhs73b6mik0-a.oregon-postgres.render.com:5432\online_voting_db_16rt
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=sai
spring.datasource.password=KX42fe6wwc9uTQqZpBDBSltvCP2wfeMk

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


